/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file has been modified from the original Apache OpenNLP source:
// translated from Java to C# and adapted for .NET. See NOTICE.

using System.Collections.Generic;
using NOpenNLP.Tools.Chunker;
using NOpenNLP.Tools.Ml.Model;
using NOpenNLP.Tools.Postag;
using NOpenNLP.Tools.Util;
using JCG = J2N.Collections.Generic;
using OpenNlpDictionary = NOpenNLP.Tools.Dictionary.Dictionary;

namespace NOpenNLP.Tools.Parser;

/// <summary>
/// Abstract class extended by parser event streams which perform tagging and chunking.
/// </summary>
public abstract class AbstractParserEventStream : AbstractEventStream<Parse>
{
    private readonly IChunkerContextGenerator? chunkerContextGenerator; // NOpenNLP: made readonly
    private readonly IPOSContextGenerator? tagContextGenerator; // NOpenNLP: made readonly
    protected IHeadRules rules;
    protected ISet<string> punctSet;

    /// <summary>
    /// The type of events being generated by this event stream.
    /// </summary>
    protected ParserEventTypeEnum etype;
    protected bool fixPossesives;
    protected OpenNlpDictionary? dict;

    protected AbstractParserEventStream(IObjectStream<Parse?> d,
        IHeadRules rules, ParserEventTypeEnum etype, OpenNlpDictionary? dict = null)
        : base(d)
    {
        this.dict = dict;
#pragma warning disable CS0612 // CHUNK and TAG are obsolete upstream but still handled here
        if (etype == ParserEventTypeEnum.CHUNK)
        {
            this.chunkerContextGenerator = new ChunkContextGenerator();
        }
        else if (etype == ParserEventTypeEnum.TAG)
        {
            this.tagContextGenerator = new DefaultPOSContextGenerator(null);
        }
#pragma warning restore CS0612

        this.rules = rules;
        punctSet = rules.PunctuationTags;
        this.etype = etype;

        Init();
    }

    /// <inheritdoc/>
    protected override IEnumerable<Event> CreateEvents(Parse sample)
    {
        IList<Event> newEvents = new JCG.List<Event>();

        Parse.PruneParse(sample);
        if (fixPossesives)
        {
            Parse.FixPossesives(sample);
        }

        sample.UpdateHeads(rules);
        var chunks = GetInitialChunks(sample);
#pragma warning disable CS0612 // CHUNK and TAG are obsolete upstream but still handled here
        if (etype == ParserEventTypeEnum.TAG)
        {
            AddTagEvents(newEvents, chunks);
        }
        else if (etype == ParserEventTypeEnum.CHUNK)
        {
            AddChunkEvents(newEvents, chunks);
        }
#pragma warning restore CS0612
        else
        {
            AddParseEvents(newEvents, Chunking.Parser.CollapsePunctuation(chunks, punctSet));
        }

        return newEvents;
    }

    protected virtual void Init() => fixPossesives = false;

    public static Parse[] GetInitialChunks(Parse p)
    {
        IList<Parse> chunks = new JCG.List<Parse>();
        GetInitialChunks(p, chunks);
        return [.. chunks];
    }

    private static void GetInitialChunks(Parse p, IList<Parse> ichunks)
    {
        if (p.IsPosTag)
        {
            ichunks.Add(p);
        }
        else
        {
            var kids = p.GetChildren();
            bool allKidsAreTags = true;
            foreach (var kid in kids)
            {
                if (!kid.IsPosTag)
                {
                    allKidsAreTags = false;
                    break;
                }
            }

            if (allKidsAreTags)
            {
                ichunks.Add(p);
            }
            else
            {
                foreach (var kid in kids)
                {
                    GetInitialChunks(kid, ichunks);
                }
            }
        }
    }

    /// <summary>
    /// Produces all events for the specified sentence chunks
    /// and adds them to the specified list.
    /// </summary>
    /// <param name="newEvents">A list of events to be added to.</param>
    /// <param name="chunks">Pre-chunked constituents of a sentence.</param>
    protected abstract void AddParseEvents(IList<Event> newEvents, Parse[] chunks);

    private void AddChunkEvents(IList<Event> chunkEvents, Parse[] chunks)
    {
        var toks = new JCG.List<string>();
        var tags = new JCG.List<string>();
        var preds = new JCG.List<string>();

        foreach (var c in chunks)
        {
            if (c.IsPosTag)
            {
                toks.Add(c.CoveredText);
                tags.Add(c.Type);
                preds.Add(Chunking.Parser.OTHER);
            }
            else
            {
                bool start = true;
                string ctype = c.Type;
                var kids = c.GetChildren();
                foreach (var tok in kids)
                {
                    toks.Add(tok.CoveredText);
                    tags.Add(tok.Type);
                    if (start)
                    {
                        preds.Add(Chunking.Parser.START + ctype);
                        start = false;
                    }
                    else
                    {
                        preds.Add(Chunking.Parser.CONT + ctype);
                    }
                }
            }
        }

        for (int ti = 0, tl = toks.Count; ti < tl; ti++)
        {
            chunkEvents.Add(new Event(preds[ti],
                chunkerContextGenerator!.GetContext(ti, [.. toks], [.. tags], [.. preds])));
        }
    }

    private void AddTagEvents(IList<Event> tagEvents, Parse[] chunks)
    {
        var toks = new JCG.List<string>();
        var preds = new JCG.List<string>();

        foreach (var c in chunks)
        {
            if (c.IsPosTag)
            {
                toks.Add(c.CoveredText);
                preds.Add(c.Type);
            }
            else
            {
                var kids = c.GetChildren();
                foreach (var tok in kids)
                {
                    toks.Add(tok.CoveredText);
                    preds.Add(tok.Type);
                }
            }
        }

        for (int ti = 0, tl = toks.Count; ti < tl; ti++)
        {
            tagEvents.Add(new Event(preds[ti], tagContextGenerator!.GetContext(ti,
                [.. toks], [.. preds], null)));
        }
    }

    /// <summary>
    /// Returns true if the specified child is the last child of the specified parent.
    /// </summary>
    /// <param name="child">The child parse.</param>
    /// <param name="parent">The parent parse.</param>
    /// <returns>true if the specified child is the last child of the specified parent;
    /// false otherwise.</returns>
    protected virtual bool LastChild(Parse child, Parse parent)
    {
        var kids = AbstractBottomUpParser.CollapsePunctuation(parent.GetChildren(), punctSet);
        return kids[^1] == child;
    }
}
