/*
 * Copyright 2026 NOpenNLP Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using NOpenNLP.Tools.Stemmer.Snowball;
using NOpenNLP.Tools.Support;
using NUnit.Framework;
using NUnit.Framework.Legacy;

namespace NOpenNLP.Tools.Stemmer;

/// <summary>
/// Pins the four languages where the generated stemmers deliberately differ from
/// Apache OpenNLP 1.9.4.
/// </summary>
/// <remarks>
/// The stemmers are generated by the Snowball compiler pinned to 2.0.0. Measured
/// over the full Snowball vocabularies - 1,113,209 words - 17 of the 21 languages
/// are byte-identical to OpenNLP 1.9.4. Four are not, because OpenNLP ships
/// generated code that predates several upstream fixes, and the sources behind it
/// survive at no revision that can be pinned: its Finnish and Hungarian stemmers
/// were committed 2013-11-20, before the Snowball project moved to git.
/// <para/>
/// In each case the difference is the fix, so these are kept rather than reverted.
/// The cases below are the concrete evidence for that claim, and exist so the
/// deviation cannot drift silently: if a regeneration changes one of these, the
/// pin or the algorithm moved, and that needs a deliberate decision rather than a
/// surprise.
/// <para/>
/// The corresponding upstream assertions all still pass - see
/// <c>SnowballStemmerTest</c>. None of them touch an affected word.
/// </remarks>
[NOpenNLPSpecific]
public class SnowballDeviationTest
{
    /// <summary>
    /// OpenNLP 1.9.4 stems these four inflections of the Finnish noun <c>aarre</c>
    /// ("treasure") to four different stems - aartees, aarteid, aarteis, aart -
    /// so a search for one form cannot match a document containing another.
    /// </summary>
    [Test]
    public void TestFinnishConflatesCaseFormsOfOneNoun()
    {
        SnowballStemmer stemmer = new SnowballStemmer(ALGORITHM.FINNISH);

        ClassicAssert.AreEqual("aart", stemmer.Stem("aarteeseen"));
        ClassicAssert.AreEqual("aart", stemmer.Stem("aarteiden"));
        ClassicAssert.AreEqual("aart", stemmer.Stem("aarteisiin"));
        ClassicAssert.AreEqual("aart", stemmer.Stem("aarteet"));
    }

    /// <summary>
    /// OpenNLP 1.9.4 leaves the Hungarian ablative and delative case suffixes
    /// (-ról/-ről, -tól/-től) entirely unstripped, stemming each of these words
    /// to itself.
    /// </summary>
    [Test]
    public void TestHungarianStripsAblativeAndDelativeSuffixes()
    {
        SnowballStemmer stemmer = new SnowballStemmer(ALGORITHM.HUNGARIAN);

        ClassicAssert.AreEqual("adatvédel", stemmer.Stem("adatvédelemről"));
        ClassicAssert.AreEqual("ak", stemmer.Stem("akikről"));
        ClassicAssert.AreEqual("adófizető", stemmer.Stem("adófizetőktől"));
    }

    /// <summary>
    /// Snowball commit 86ceab9, "Recognize suffixes that begin with diaereses",
    /// which OpenNLP 1.9.4 predates. <c>aigu</c> and <c>aiguë</c> are the
    /// masculine and feminine of one adjective; upstream stems the latter to
    /// itself.
    /// </summary>
    [Test]
    public void TestFrenchRecognizesSuffixesBeginningWithDiaereses()
    {
        SnowballStemmer stemmer = new SnowballStemmer(ALGORITHM.FRENCH);

        ClassicAssert.AreEqual("aigu", stemmer.Stem("aiguë"));
        ClassicAssert.AreEqual("aigu", stemmer.Stem("aiguës"));
        ClassicAssert.AreEqual("archa", stemmer.Stem("archaïque"));
        ClassicAssert.AreEqual("archa", stemmer.Stem("archaïsme"));
    }

    /// <summary>
    /// The Indonesian deviation runs the other way: the port stems less. In these
    /// loanwords the final <c>-i</c> belongs to the root, and OpenNLP 1.9.4 strips
    /// it anyway (demokrasi -> demokras), corrupting the stem.
    /// </summary>
    [Test]
    public void TestIndonesianKeepsRootFinalIOfLoanwords()
    {
        SnowballStemmer stemmer = new SnowballStemmer(ALGORITHM.INDONESIAN);

        ClassicAssert.AreEqual("demokrasi", stemmer.Stem("demokrasi"));
        ClassicAssert.AreEqual("organisasi", stemmer.Stem("organisasi"));
        ClassicAssert.AreEqual("abdikasi", stemmer.Stem("abdikasi"));
    }

    /// <summary>
    /// The counterpart to <see cref="TestIndonesianKeepsRootFinalIOfLoanwords"/>:
    /// a genuine <c>-i</c> suffix is still stripped, so the fix recovered
    /// precision without giving up suffix handling. Both implementations agree
    /// on these.
    /// </summary>
    [Test]
    public void TestIndonesianStillStripsGenuineSuffixes()
    {
        SnowballStemmer stemmer = new SnowballStemmer(ALGORITHM.INDONESIAN);

        ClassicAssert.AreEqual("ambil", stemmer.Stem("mengambili"));
        ClassicAssert.AreEqual("emu", stemmer.Stem("menemui"));
    }
}
